### ISSUE TITLE
How use esno run top await code?

### ISSUE THREAD

**Issue by awkj** [esbuild-kit/esno#33] opened 2022-05-21 07:51 UTC
When I update esmo, esmo be replace by esno, but same code , esmo is work, esno no.

my code is 
```typescipt
await runsome()
```

but have fault
```json
{
    "location": {
        "column": 14,
        "file": "xxx.ts",
        "length": 5,
        "line": 23,
        "lineText": "let configs = await Promise.all(result.map(async (category: string) => {",
        "namespace": "",
        "suggestion": ""
    },
    "notes": [],
    "pluginName": "",
    "text": "Top-level await is currently not supported with the \"cjs\" output format"
}
```

I get the mistake, how to config it ?

**Comment by yolio2003** [comment] 2022-05-23 12:05
i have tried 0.15.0 should be ok, didn't try to find why

**Comment by antfu** [comment] 2022-05-23 13:34
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-05-23 13:34 UTC
